# Generated by Django 3.2.12 on 2022-10-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=True)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
